{% set name = "m2r" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/m2r-{{ version }}.tar.gz
  sha256: aafb67fc49cfb1d89e46a3443ac747e15f4bb42df20ed04f067ad9efbee256ab

build:
  entry_points:
    - m2r = m2r:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mistune <2
    - docutils

test:
  imports:
    - m2r
  commands:
    - pip check
    - m2r --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/miyakogi/m2r
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Markdown and reStructuredText in a single file

extra:
  recipe-maintainers:
    - ocefpaf
